LEFT_SQUARE_BRACKET_TOKEN = '['
RIGHT_SQUARE_BRACKET_TOKEN = ']'
LEFT_PAREN_TOKEN = '('
RIGHT_PAREN_TOKEN = ')'

PLUS_TOKEN = '+'
MULTIPLY_TOKEN = '*'
POWER_TOKEN = '^'

FULL_ARROW_TOKEN_WITH_SPACES = ' -> '
OR_TOKEN_WITH_SPACES = ' | '

MINUS_TOKEN = '-'
ARROW_TOKEN = '>'
OR_TOKEN = '|'

DOT_TOKEN = '.'
DOLLAR_TOKEN = '$'
START_TOKEN = 'S'

NULL_TOKEN = 'START'