EQUAL_TOKEN = '='
VARIABLE_TOKEN = 'x'
LEFT_PAREN_TOKEN = '('
RIGHT_PAREN_TOKEN = ')'
CONSTRUCTOR_TOKEN = r"[a-z]"

PLUS_TOKEN = '+'
MINUS_TOKEN = '-'
MULTIPLY_TOKEN = '*'
POWER_TOKEN = '^'
NUMBER_TOKEN = r"[1-9]"
DIGIT_TOKEN = r"[0-9]"

VARIABLE_ALIAS = '1*x^1'
